### PR TITLE
Provide gradle build file

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by Nicklas2751** [comment]
Whats about the zip building and the build informations in the version.properties file? Btw. why gradle and not maven?

**Comment by simon04** [comment]
Added zip building in 37cd9b0. Writing maven `pom.xml` files is no fun.

**Comment by Nicklas2751** [comment]
But a maven pom.xml haves an structure everybody can understand if he know maven or not. A gradle file has no direcly clear structure and is so very hard to understand for people who don't know gradle. 

But this is just a maven vs gradle thing. Im not happy with your actual configuration too. You build now the zip and its including the version.properties. But what you don't do is updating the version.properties file and you don't include the used libaries als "lib" folder in the zip. Please take a look on the content of the pre- and post-make.sh files.

**Comment by Nicklas2751** [comment]
Weitere Informationen / Further informations: https://hub.mediathekview.de/s/7a34baa6-3467-4bd0-b4bf-d985d12e07bc/?wallEntryId=95

**Comment by simon04** [comment]
True, I forgot running `pre_make.sh`. Fixed in 09dda31.

All libraries are added to the ZIP file:
```
$ unzip -l build/distributions/MSearch.zip
Archive:  build/distributions/MSearch.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2016-10-27 10:04   MSearch/
    32681  2016-10-23 22:13   MSearch/README.txt
        0  2016-10-27 10:04   MSearch/lib/
   308370  2016-10-27 10:04   MSearch/lib/MSearch.jar
   434678  2016-10-24 11:02   MSearch/lib/commons-lang3-3.4.jar
   252084  2016-10-24 11:02   MSearch/lib/jackson-core-2.7.0.jar
  1937532  2016-10-24 11:02   MSearch/lib/jide-oss-3.6.16.jar
    99555  2015-11-30 16:16   MSearch/lib/xz-1.5.jar
        0  2016-10-27 10:04   MSearch/bin/
     5279  2016-10-27 10:04   MSearch/bin/MSearch
     2328  2016-10-27 10:04   MSearch/bin/MSearch.bat
---------                     -------
  3072507                     11 files
```

In `MSearch/bin` gradle automatically builds start scripts to set the classpath accordinly. For more details see https://docs.gradle.org/current/userguide/application_plugin.html

**Comment by Nicklas2751** [comment]
Die Merheit hat sich für gradle entschieden. ;)

**Comment by alex1702** [comment]
Merged gradle Support von kaklakarada

**Pull request closed without merging**
